# Generated by Django 4.2.11 on 2024-04-23 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photogram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
