# Generated by Django 4.2.11 on 2024-04-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photogram", "0002_alter_photo_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="likes_count",
        ),
    ]
