# Generated by Django 4.2.11 on 2024-04-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photogram", "0004_like_followrequest_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
    ]
